FROM node:24-alpine

RUN npm install -g pnpm@latest

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 5173
EXPOSE 4173

CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0"]
